services:
  lighthouse:
    image: sigp/lighthouse:latest
    container_name: lighthouse
    restart: unless-stopped
    user: "0:0"
    volumes:
      - ./Consensus:/root/.lighthouse
      - ./jwt.hex:/jwt.hex
    command:
      - lighthouse
      - bn
      - --network=sepolia
      - --datadir=/root/.lighthouse
      - --checkpoint-sync-url=https://sepolia.beaconstate.info
      - --http
      - --http-address=0.0.0.0
      - --http-port=5052
      - --execution-endpoint=http://execution:8551
      - --execution-jwt=/jwt.hex
      - --port=9000
      - --disable-deposit-contract-sync
      - --prune-payloads
      - --prune-finalized
      - --prune-checkpoints
      - --blobsidecar
    ports:
      - 5052:5052
      - 9000:9000/tcp
      - 9000:9000/udp
