services:
  erigon:
    image: ghcr.io/erigontech/erigon:v3.0.2
    container_name: erigon
    restart: unless-stopped
    user: "0:0"
    volumes:
      - ./Execution:/data
      - ./jwt.hex:/data/jwt.hex
    command:
      - --chain=sepolia
      - --datadir=/data
      - --prune=hrtc
      - --prune.h.older=3
      - --prune.r.older=3
      - --prune.t.older=3
      - --externalcl
      - --authrpc.jwtsecret=/data/jwt.hex
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.vhosts=*
      - --http.api=eth,net,web3,erigon,debug,trace,txpool
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --port=30303
    ports:
      - 8545:8545
      - 8546:8546
      - 8551:8551
      - 30303:30303/tcp
      - 30303:30303/udp

  lighthouse:
    image: sigp/lighthouse:latest
    container_name: lighthouse
    restart: unless-stopped
    user: "0:0"
    volumes:
      - ./Consensus:/root/.lighthouse
      - ./jwt.hex:/jwt.hex
    command:
      - lighthouse
      - bn
      - --network=sepolia
      - --datadir=/root/.lighthouse
      - --checkpoint-sync-url=https://sepolia.beaconstate.info
      - --http
      - --http-address=0.0.0.0
      - --http-port=5052
      - --execution-endpoint=http://execution:8551
      - --execution-jwt=/jwt.hex
      - --port=9000
      - --disable-deposit-contract-sync
      - --prune-payloads
      - --prune-finalized
      - --prune-checkpoints
      - --blobsidecar
    ports:
      - 5052:5052
      - 9000:9000/tcp
      - 9000:9000/udp

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    restart: unless-stopped
    depends_on:
      - erigon
      - lighthouse
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./whitelist.lst:/etc/haproxy/whitelist.lst
    ports:
      - "80:80"
      - "443:443"
    networks:
      - sepolia-net

networks:
  sepolia-net:
    name: sepolia-rpc-net
